config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "companies#index"
  resources :companies do
    resources :employees do
      resources :payrolls
    end
    resources :parameters
    resources :payrolls
    resources :contractors do
      resources :service_payments
    end
    resources :service_payments
    resources :reports, only: [:index, :new, :create, :destroy, :show]
    resources :report_configurations
  end

  get "reports/:id/download" => "reports#download", as: :download_report
  get "pages/terms_and_conditions", to: "pages#terms_and_conditions"
  post "pages/update_terms_and_conditions", to: "pages#update_terms_and_conditions"
  get "pages/privacy_policy", to: "pages#privacy_policy"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
  has_many :employees, dependent: :destroy
  has_many :contractors, dependent: :destroy
  has_many :payrolls, through: :employees
  has_many :parameters, dependent: :destroy
  has_many :service_payments, through: :contractors
  has_many :reports, dependent: :destroy
  has_many :report_configurations, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true

  after_create_commit :create_parameters

  def create_parameters
    parameters.create([
      { parameter_name: "overtime_coefficient", parameter_value: 1.5 },
      { parameter_name: "social_security_medicare", parameter_value: 0.05 },
      { parameter_name: "driver_insurance", parameter_value: 0.05 },
      { parameter_name: "sinot", parameter_value: 1.8 }
    ])
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  def index
    @companies = Company.where(user: current_user)

    if params[:search].present?
      @companies = @companies.where("name ILIKE ?", "%#{params[:search]}%")
    end
    @companies = @companies.page(params[:page]).per(10)
  end

  # GET /companies/1
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # POST /companies
  def create
    @company = Company.new(company_params)
    @company.user = current_user # Asocia la empresa al usuario actual, si tienes autenticación

    if @company.save
      redirect_to @company, notice: 'Company was successfully created.'
    else
      render :new
    end
  end

  # GET /companies/1/edit
  def edit
  end

  # PATCH/PUT /companies/1
  def update
    if @company.update(company_params)
      redirect_to @company, notice: 'Company was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /companies/1
  def destroy
    @company.destroy
    redirect_to companies_url, notice: 'Company was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_company
    @company = Company.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def company_params
    params.require(:company).permit(
      :user_id,
      :name,
      :entity_type,
      :postal_address,
      :postal_city,
      :postal_country,
      :postal_zip_code,
      :physical_address,
      :physical_city,
      :physical_country,
      :physical_zip_code,
      :same_as_postal,
      :ein_ss,
      :state_employer_number,
      :merchant_registration_number,
      :start_date,
      :contact_person,
      :contact_phone,
      :contact_email,
      :website,
      :employer,
      :payer,
      :jurisdiction,
      :employment_code,
      :photo
    )
  end

end

app/views/companies/_form.html.erb
<div class="form-container">
  <%= simple_form_for(@company, html: { class: 'details-container', local: true }) do |form| %>

    <div class="title-item">
      <h5> Detalles de la compañía </h5>
    </div>

    <%= form.input :name, label: "Nombre de la Compañía", wrapper_html: { class: 'detail-item' }, label_html: { class: 'label-bold' }, input_html: { class: 'input-span' } %>

    <%= form.input :entity_type, label: "Tipo de Entidad",
              collection: [["Corporación", "Corporación"], ["Individuo", "Individuo"]],
              prompt: "Seleccione una opción", wrapper_html: { class: 'detail-item' },
              label_html: { class: 'label-bold' }, input_html: { class: 'input-span' } %>

    <%= form.input :ein_ss, label: "EIN/SS", as: :integer, maxlength: 9, wrapper_html: { class: 'detail-item' }, label_html: { class: 'label-bold' }, input_html: { class: 'input-span' } %>

    <%= form.input :state_employer_number, label: "Número Patronal Estatal", as: :integer, maxlength: 10, wrapper_html: { class: 'detail-item' }, label_html: { class: 'label-bold' }, input_html: { class: 'input-span' } %>

    <%= form.input :merchant_registration_number, label: "Número de Registro de Comerciante", as: :integer, maxlength: 11, wrapper_html: { class: 'detail-item' }, label_html: { class: 'label-bold' }, input_html: { class: 'input-span' } %>

    <%= form.input :start_date,
      label: "Fecha de Comienzo",
      as: :string, start_year: 1900,
      wrapper_html: { class: 'detail-item' },
      label_html: { class: 'label-bold' },
      input_html: {
        class: 'input-span',
        data: { controller: "datepicker"} } %>

    <%= form.input :employment_code,
      label: "Código de empleo",
      collection: [
        "Agrícola, Modelo 943",
        "Composición Familiar, Anejo H",
        "Contribuciones Medicare Empleado Gubernamental Calificado, Formulario 941",
        "Ferroviarios CT-1",
        "Militares, Formulario 941",
        "Regular (todos los demás) Formulario 941",
        "Regular, Modelo 944"
      ],
      prompt: "Seleccione una opción",
      wrapper_html: { class: 'detail-item' },
      label_html: { class: 'label-bold' },
      input_html: { class: 'input-span' }
    %>

    <%= form.input :employer,
        label: "Empleador",
        collection: [
          "Federal Government",
          "State and Local Gov",
          "Tax Exempt Employee",
          "State and Local Tax",
          "None Apply"
        ],
        prompt: "Select an option",
        wrapper_html: { class: 'detail-item' },
        label_html: { class: 'label-bold' },
        input_html: { class: 'input-span' }
      %>

    <%= form.input :payer,
      label: "Payer/Pagador",
      collection: [
        "941-PR",
        "943-PR",
        "944-PR",
        "Doméstico",
        "Comp. por enferm.",
        "Sólo empleados Med."
      ],
      prompt: "Seleccione una opción",
      wrapper_html: { class: 'detail-item' },
      label_html: { class: 'label-bold' },
      input_html: { class: 'input-span' }
    %>

    <%= form.input :jurisdiction,
      label: "Jurisdicción",
      collection: [
        "N = Northern Mariana",
        "S = American Samoa",
        "V = Virgin Islands",
        "P = Puerto Rico",
        "G = Guam"
      ],
      prompt: "Seleccione una opción",
      wrapper_html: { class: 'detail-item' },
      label_html: { class: 'label-bold' },
      input_html: { class: 'input-span' }
    %>






    <div class="title-item">
      <h5> Información de dirección </h5>
    </div>

    <%= form.input :postal_address, label: "Dirección Postal", wrapper_html: { class: 'detail-item' }, label_html: { class: 'label-bold' }, input_html: { class: 'input-span' } %>

    <%= form.input :postal_city, label: "Ciudad (Postal)", wrapper_html: { class: 'detail-item' }, label_html: { class: 'label-bold' }, input_html: { class: 'input-span' } %>

    <%= form.input :postal_country, label: "País (Postal)", wrapper_html: { class: 'detail-item' }, label_html: { class: 'label-bold' }, input_html: { class: 'input-span' } %>

    <%= form.input :postal_zip_code, label: "Código Postal", wrapper_html: { class: 'detail-item' }, label_html: { class: 'label-bold' }, input_html: { class: 'input-span' } %>

    <%= form.input :physical_address, label: "Dirección Física", wrapper_html: { class: 'detail-item' }, label_html: { class: 'label-bold' }, input_html: { class: 'input-span' } %>

    <%= form.input :physical_city, label: "Ciudad (Física)", wrapper_html: { class: 'detail-item' }, label_html: { class: 'label-bold' }, input_html: { class: 'input-span' } %>

    <%= form.input :physical_country, label: "País (Física)", wrapper_html: { class: 'detail-item' }, label_html: { class: 'label-bold' }, input_html: { class: 'input-span' } %>

    <%= form.input :physical_zip_code, label: "Código Postal (Física)", wrapper_html: { class: 'detail-item' }, label_html: { class: 'label-bold' }, input_html: { class: 'input-span' } %>

    <%= form.input :same_as_postal, label: "¿Dirección Física igual a la Postal?", as: :boolean, wrapper_html: { class: 'detail-item' }, label_html: { class: 'label-bold' } %>

    <div class="title-item">
      <h5> Información de contacto </h5>
    </div>

    <%= form.input :contact_person, label: "Persona de Contacto", wrapper_html: { class: 'detail-item' }, label_html: { class: 'label-bold' }, input_html: { class: 'input-span' } %>

    <%= form.input :contact_phone, label: "Número de Teléfono (Contacto)", wrapper_html: { class: 'detail-item' }, label_html: { class: 'label-bold' }, input_html: { class: 'input-span' } %>

    <%= form.input :contact_email, label: "Email (Contacto)", as: :email, wrapper_html: { class: 'detail-item' }, label_html: { class: 'label-bold' }, input_html: { class: 'input-span' } %>

    <%= form.input :website, label: "Website", wrapper_html: { class: 'detail-item' }, label_html: { class: 'label-bold' }, input_html: { class: 'input-span' } %>


    <div class="col-md-6 col-sm-12 d-flex flex-wrap">
      <% if @company.photo.key.present? %>
        <%= cl_image_tag @company.photo.key, height: 250, width: 250, crop: :fill %>
      <% end %>

      <%= form.input :photo, label: "Foto", as: :file, wrapper_html: { class: 'detail-item' }, label_html: { class: 'label-bold' }, input_html: { class: 'input-span special-height' } %>
    </div>


    <div class="button-group title-item">
      <%= link_to "Cancelar", companies_path, class: "btn btn-danger" %>
      <%= form.button :submit, @company.new_record? ? "Crear Compañía" :  "Actualizar Compañia", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>



<style>

  #companies-show {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 20px;
    padding: 2rem;
  }

  .special-height {
    max-height: 45px;
  }



</style>

app/views/companies/edit.html.erb
<section id="new-company">
  <h1>Editar Compañía</h1>
 <%= render  "form", company: @company %>
</section>

app/views/companies/index.html.erb
<div id="company-index">

  <div class="view-options">
    <h1>Mis de Compañías</h1>

    <div class="search-bar">
      <%= form_with url: companies_path, method: :get, local: true do %>
        <%= label_tag :search, "Buscar Compañia:" %>
        <%= text_field_tag :search, params[:search], placeholder: "Nombre de la compañia" %>
        <%= submit_tag "Buscar", class: "btn btn-secondary" %>
        <% if params[:search].present? %>
         <%= link_to "Limpiar filtros", companies_path, class: "btn btn-secondary" %>
        <% end %>
      <% end %>
    </div>


    <%= link_to "Crear nueva compañia", new_company_path, class: "btn btn-primary" %>

  </div>

  <table>
    <thead class="header-table">
      <tr>
        <th>N°</th>
        <th>Nombre</th>
        <th>Tipo de compañia</th>
        <th class="hideable-column">Dirección</th>
        <th class="hideable-column">Teléfono</th>
        <th class="hideable-column">Email</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      <% @companies.each_with_index do |company, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= company.name %></td>
          <td><%= company.entity_type %></td>
          <td class="hideable-column"><%= company.postal_address %></td>
          <td class="hideable-column"><%= company.contact_phone %></td>
          <td class="hideable-column"><%= company.contact_email %></td>
          <td class="actions-table">
            <%= link_to "Ver", company_path(company), class: "btn btn-primary" %>
            <%= link_to "Editar", edit_company_path(company), class: "btn btn-primary" %>
            <%= link_to "Eliminar", company_path(company), data: {turbo_method: :delete, turbo_confirm: "¿Estás seguro?"},
                      class: "btn btn-danger btn-sm"%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @companies %>

  <% unless current_user.terms_accepted && current_user.privacy_accepted%>
    <div class="terms-and-conditions">
      <%= render "pages/terms_and_conditions" %>
      <hr>
      <%= render "pages/privacy_policy" %>
      <%= render "pages/terms_and_conditions" %>
      <%= link_to "Acceptar terminos y condiciones y policas de privacidad", pages_update_terms_and_conditions_path,
          data: { 'turbo-method' => :post }, class: "btn btn-primary" %>
    </div>
  <% end %>

</div>




<style>



    #company-index {
      /* background: linear-gradient(to bottom, #14ABFF, #00DE82); */

      padding: 2rem;
    }

    .terms-and-conditions {
      position: absolute;
      top: 4rem;
      margin-right: 1.1rem;
      margin-bottom: 1.1rem;
      padding: 2rem;
      border: #007bff 1px solid;
      background-color:rgba(210, 218, 226, 0.95);
    }



</style>

app/views/companies/new.html.erb
<section id="new-company">
  <h1>Crear Nueva Compañía</h1>
 <%= render  "form", company: @company %>
</section>


<style>

  #new-company {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 20px;
    padding: 2rem;
  }


</style>

app/views/companies/show.html.erb
<section id="companies-show">


  <div class="actions">
    <%= link_to "Editar", edit_company_path(@company) %>

    <%= button_to "Eliminar", company_path(@company), method: :delete, data: { confirm: "¿Estás seguro de que deseas eliminar esta compañía?" }, form_class: "delete-form" %>
    <%= link_to "Listado de compañias", companies_path %>
    <%= link_to "Configurar parametros",   company_parameters_path(@company) %>
    <%= link_to "Configurar Reportes", company_report_configurations_path(@company) %>

  </div>


<div class="details-container">
  <div class="title-item">
    <h5> Detalles de la compañia </h5>
  </div>

  <div class="row w-100">
    <div class="col-md-6 col-sm-12">
      <div class="detail-item">
        <strong>Nombre de la Compañía:</strong>
        <span><%= @company.name %></span>
      </div>
      <div class="detail-item">
        <strong>Tipo de Entidad:</strong>
        <span><%= @company.entity_type %></span>
      </div>
      <div class="detail-item">
        <strong>EIN/SS:</strong>
        <span><%= @company.ein_ss %></span>
      </div>
      <div class="detail-item">
        <strong>Número Patronal Estatal:</strong>
        <span><%= @company.state_employer_number %></span>
      </div>
      <div class="detail-item">
        <strong>Número de Registro de Comerciante:</strong>
        <span><%= @company.merchant_registration_number %></span>
      </div>
      <div class="detail-item">
        <strong>Fecha de Comienzo:</strong>
        <span><%= @company.start_date.strftime('%m/%d/%Y') if @company.start_date %></span>
      </div>
    </div>

    <div class="col-md-6 col-sm-12">
      <% if @company.photo.key.present? %>
        <%= cl_image_tag @company.photo.key, height: 250, width: 250, crop: :fill %>
      <% else %>
        <%= image_tag "250.jpg" , height: 250, width: 250 %>
      <% end %>
    </div>

  </div>




  <div class="title-item">
    <h5> Información de dirección </h5>
  </div>
  <div class="detail-item">
      <strong>Dirección Postal / Ciudad / Pais / ZIP :</strong>
      <span><%= @company.postal_address %> / <%= @company.postal_city %> / <%= @company.postal_country %> / <%= @company.postal_zip_code %></span>
    </div>

  <div class="detail-item">
    <strong>Dirección Física / Ciudad / Pais / ZIP :</strong>
    <span><%= @company.physical_address %> / <%= @company.physical_city %> / <%= @company.physical_country %> / <%= @company.physical_zip_code %></span>
  </div>
  <div class="detail-item">
    <strong>¿Dirección Física igual a la Postal?</strong>
    <span><%= @company.same_as_postal ? "Sí" : "No" %></span>
  </div>

  <div class="detail-item">
    <strong>Código de empleo:</strong>
    <span><%= @company.employment_code %></span>

  </div>

  <div class="detail-item">
    <strong>Empleador:</strong>
    <span><%= @company.employer %></span>
  </div>

  <div class="detail-item">
    <strong>Payer/Pagador:</strong>
    <span><%= @company.payer %></span>
  </div>

  <div class="detail-item">
    <strong>Jurisdicción:</strong>
    <span><%= @company.jurisdiction %></span>
  </div>


  <div class="title-item">
    <h5> Información de contacto </h5>
  </div>

  <div class="detail-item">
    <strong>Persona de Contacto:</strong>
    <span><%= @company.contact_person %></span>
  </div>
  <div class="detail-item">
    <strong>Número de Teléfono (Contacto):</strong>
    <span><%= @company.contact_phone %></span>
  </div>
  <div class="detail-item">
    <strong>Email (Contacto):</strong>
    <span><%= @company.contact_email %></span>
  </div>

  <div class="detail-item">
    <strong>Website:</strong>
    <span><%= @company.website %></span>
  </div>
</div>



</section>



<style>

    #companies-show {
      display: flex;
      flex-direction: column;
      align-items: center;
      gap: 20px;
      padding-right: 1.5rem;
      padding-left: 1.5rem;
    }



    .details-container {
      display: flex;
      flex-wrap: wrap;
      background-color: #fff;
      padding: 20px;
      border-radius: 8px;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
      column-gap: 1%;
      width: 100%;
    }

    .detail-item {
      min-width: 48.5%;
      margin-bottom: 8px;
      display: flex;

    }

    .detail-item strong {
      width: 30%;

    }

    .detail-item span {
      width: 69%;
      text-wrap: wrap;
      overflow-wrap: break-word;
    }

    .title-item {
      width: 100%;
      color: #00DE82;
      font-weight: bold;
      font-size: 1.2rem;
      border-bottom: 1px solid #ddd;
      margin-bottom: 16px;
    }

    .detail-item strong {
      display: block;
      font-size: 16px;
      color: #555;
      margin-bottom: 5px;
    }

    .actions {

      display: flex;
      gap: 10px;
    }

    .actions a, .actions form button {
      padding: 10px 15px;
      font-size: 16px;
      border: none;
      border-radius: 5px;
      color: #fff;
      text-decoration: none;
      cursor: pointer;
    }

    .actions a {
      background-color: #1a73e8;
    }

    .actions a:hover {
      background-color: #155cb0;
    }

    .actions form button {
      background-color: #e53935;
    }

    .actions form button:hover {
      background-color: #c62828;
    }
  </style>