config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "companies#index"
  resources :companies do
    resources :employees do
      resources :payrolls
    end
    resources :parameters
    resources :payrolls
    resources :contractors do
      resources :service_payments
    end
    resources :service_payments
    resources :reports, only: [:index, :new, :create, :destroy, :show]
    resources :report_configurations
  end

  get "reports/:id/download" => "reports#download", as: :download_report
  get "pages/terms_and_conditions", to: "pages#terms_and_conditions"
  post "pages/update_terms_and_conditions", to: "pages#update_terms_and_conditions"
  get "pages/privacy_policy", to: "pages#privacy_policy"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/report.rb
  class Report < ApplicationRecord
    belongs_to :company

    validates :report_type, :filters, presence: true

    def generate_report
      # Generate report
      case report_type
      when 'tipo_1'
        generate_payroll_report # Pagos de nominas
      when 'tipo_2'
        generate_service_payments_report # Pagos de servicios prestados
      when 'tipo_3'
        generate_vacations # Vacaciones y enfermedad acumuladas
      when 'tipo_4'
        generate_hours_report # Hours Report
      when 'tipo_5'
        generate_social_security_medicare_report # Social Security and Medicare Deposits Report
      when 'tipo_6'
        generate_income_tax_report # Income Tax Deposits Report
      when 'tipo_7'
        generate_service_payments_deposits_report # Service Payments Deposits Report
      end
    end

    def type_name
      case report_type
      when 'tipo_1'
        'Pagos de nómina'
      when 'tipo_2'
        'Pagos de servicios prestados'
      when 'tipo_3'
        'Vacaciones y enfermedad acumuladas'
      when 'tipo_4'
        'Informe de horas'
      when 'tipo_5'
        'Informe de depósitos de Seguro Social y Medicare'
      when 'tipo_6'
        'Informe de depósitos de Impuesto sobre Ingresos'
      when 'tipo_7'
        'Informe de depósitos de Pagos por Servicios'
      end
    end

    def filters_formatted
      case report_type
      when 'tipo_1'
        "Empleado: #{filters['employee'] == "all" ? "Todos" : company.employees.find(filters['employee']).full_name}<br>Periodo: #{filters['start_date']} - #{filters['end_date']}".html_safe
      when 'tipo_2'
        "Contratista: #{filters['contractor'] == "all" ? "Todos" : company.contractors.find(filters['contractor']).full_name}<br>Periodo: #{filters['start_date']} - #{filters['end_date']}".html_safe
      when 'tipo_3'
        "Empleado: #{filters['employee'] == "all" ? "Todos" : company.employees.find(filters['employee']).full_name}".html_safe
      when 'tipo_4'
        "Periodo: #{filters['start_date']} - #{filters['end_date']}".html_safe
      when 'tipo_5', 'tipo_6', 'tipo_7'
        "Año: #{filters['year']}".html_safe
      end
    end

    private

    def generate_payroll_report
      package = Axlsx::Package.new
      workbook = package.workbook

      # Iterar sobre empleados y agregar filas con los datos correspondientes
      if filters['employee'] == "all"
      employees = self.company.employees
      else
      employees = self.company.employees.where(id: filters['employee'])
      end

      # Definición de las columnas
      headers = [
        "N°", "Nombres y apellidos completos", "DIRECCIÓN FÍSICA", "CIUDAD, PAÍS Y ZIPCODE",
        "TELÉFONO", "EMAIL", "SEGURO SOCIAL", "HORAS REGULARES ACUMULADAS", "HORAS EXTRAS ACUMULADAS",
        "HORAS DE PAGA POR VACACIONES ACUMULADAS", "HORAS PAGA POR ENFERMEDADES",
        "Paga Regular", "Paga Extra", "Paga por Vacaciones", "Paga por Enfermedad",
        "SUELDO FIJO",
        "Propinas", "Comisiones", "Bonos", "Otros Pagos Sujetos a Contribuciones",
        "Otros Pagos no sujetos a retenciones", "Reembolso de gastos", "Allowances",
        "OTROS PAGOS NO SUJETOS A RETENCIONES", "TOTAL DE INGRESOS",
        "Income Tax", "Seguro Social", "Medicare", "SINOT", "Plan Médico", "ASUME",
        "Donativos", "Deducciones",
        "TOTAL DE DEDUCCIONES"
      ]

      workbook.add_worksheet(name: "Pagos de Nomina") do |sheet|


        # Add the title row with the predefined style
        header = ["Reporte de Nómina", "Periodo:", filters['start_date'], "-", filters['end_date']]
        sheet.add_row header, bg_color: "95AFBA"
        3.times { sheet.add_row }
        sheet.add_row headers

        employees.each_with_index do |employee, index|
          # last_payroll = employee.payrolls.where('pay_date >= ? AND pay_date <= ?', filters['start_date'], filters['end_date']).sum(:regular_hours_payment)
          sheet.add_row [
            index + 1,                        # Número de empleado
            employee.full_name,         # Nombres y apellidos completos
            employee.address_line,           # DIRECCIÓN FÍSICA
            "#{employee.city}, #{employee.country} #{employee.zip_code}", # CIUDAD, PAÍS Y ZIPCODE
            employee.mobile_phone,             # TELÉFONO
            employee.email,             # EMAIL
            employee.social_security || "-",         # SEGURO SOCIAL
            employee.calculate_payroll_sum("regular_hours", filters), # HORAS REGULARES ACUMULADAS
            employee.calculate_payroll_sum("overtime_hours", filters),   # HORAS EXTRAS ACUMULADAS
            employee.calculate_payroll_sum("vacation_hours", filters), # HORAS DE PAGA POR VACACIONES ACUMULADAS
            employee.calculate_payroll_sum("sick_hours", filters),   # HORAS PAGA POR ENFERMEDADES
            employee.calculate_payroll_sum("regular_hours_payment", filters),  # Paga Regular
            employee.calculate_payroll_sum("overtime_hours_payment", filters),    # Paga Extra
            employee.calculate_payroll_sum("vacation_hours_payment", filters), # Paga por Vacaciones
            employee.calculate_payroll_sum("sick_hours_payment", filters),     # Paga por Enfermedad
            employee.calculate_payroll_sum("fixed_salary", filters),
            employee.calculate_payroll_sum("tips", filters),         # Propinas
            employee.calculate_payroll_sum("commissions", filters),  # Comisiones
            employee.calculate_payroll_sum("bonuses", filters),      # Bonos
            employee.calculate_payroll_sum("other_payments_subject_to_contribution", filters),  # Otros Pagos Sujetos a Contribuciones
            employee.calculate_payroll_sum("other_payments_subject_to_contribution_2", filters), # Otros Pagos no sujetos a retenciones
            employee.calculate_payroll_sum("expense_reimbursement", filters), # Reembolso de gastos
            employee.calculate_payroll_sum("allowances", filters),   # Allowances
            employee.calculate_payroll_sum("other_payments_not_subject_to_retention", filters),
            employee.calculate_payroll_sum("gross_pay", filters),
            employee.calculate_payroll_sum("income_tax", filters),   # Income Tax
            employee.calculate_payroll_sum("social_security_medicare", filters), # Seguro Social
            employee.calculate_payroll_sum("medicare", filters),     # Medicare
            employee.calculate_payroll_sum("sinot", filters),        # SINOT
            employee.calculate_payroll_sum("medical_plan", filters),  # Plan Médico
            employee.calculate_payroll_sum("asume", filters),        # ASUME
            employee.calculate_payroll_sum("donations", filters),    # Donativos
            employee.calculate_payroll_sum("other_deductions_1", filters) +  employee&.calculate_payroll_sum("other_deductions_2", filters) + employee&.calculate_payroll_sum("other_deductions_2", filters), # Deducciones
            employee.calculate_payroll_sum("total_deductions", filters)
          ]
        end

        sheet.add_style "A1:E1", b: true, sz: 14, alignment: { horizontal: :center }, bg_color: "95AFBA"
        sheet.add_style "A5:Y5", b: true, sz: 12, alignment: { horizontal: :center }, bg_color: "051245", fg_color: "FFFFFF"
        sheet.add_style "Z5:AH5", b: true, sz: 12, alignment: { horizontal: :center }, bg_color: "00B0F0", fg_color: "FFFFFF"
      end

      workbook.add_worksheet(name: "Reporte de nominas detallado") do |sheet|
        sheet.add_row headers.map { |head_word| head_word.sub(" ACUMULADAS", "") } << "FECHA DE PAGO"
        row_number = 1
        employees.each do |employee|
          employee.payrolls.each do |payroll|
            sheet.add_row [
              row_number,
              employee.full_name,
              employee.address_line,           # DIRECCIÓN FÍSICA
              "#{employee.city}, #{employee.country} #{employee.zip_code}", # CIUDAD, PAÍS Y ZIPCODE
              employee.mobile_phone,             # TELÉFONO
              employee.email,
              employee.social_security || "-",         # SEGURO SOCIAL
              payroll.regular_hours || 0,
              payroll.overtime_hours || 0,
              payroll.vacation_hours || 0,
              payroll.sick_hours || 0,
              payroll.regular_hours_payment || 0,
              payroll.overtime_hours_payment || 0,
              payroll.vacation_hours_payment || 0,
              payroll.sick_hours_payment || 0,
              payroll.fixed_salary || 0,
              payroll.tips || 0,
              payroll.commissions || 0,
              payroll.bonuses || 0,
              payroll.other_payments_subject_to_contribution || 0,
              payroll.other_payments_not_subject_to_retention || 0,
              payroll.expense_reimbursement || 0,
              payroll.allowances || 0,
              payroll.other_payments_not_subject_to_retention || 0,
              payroll.gross_pay || 0,
              payroll.income_tax || 0,
              payroll.social_security_medicare || 0,
              payroll.medicare || 0,
              payroll.sinot || 0,
              payroll.medical_plan || 0,
              payroll.asume || 0,
              payroll.donations || 0,
              [payroll.other_deductions_1, payroll.other_deductions_2, payroll.other_deductions_3].compact.sum(&:to_f),
              payroll.total_deductions || 0,
              payroll.pay_date || "-",
            ]
            row_number += 1
          end
        end
      end

      # Devuelve el contenido del archivo
      package.to_stream.read
    end

    def generate_service_payments_report
      package = Axlsx::Package.new
      workbook = package.workbook

      # Iterar sobre empleados y agregar filas con los datos correspondientes
      if filters['contractor'] == "all"
        contractors = self.company.contractors
      else
        contractors = self.company.contractors.where(id: filters['contractor'])
      end

      # Definición de las columnas

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def index
    @company = Company.find(params[:company_id])
    @reports = @company.reports
    if params[:report_type].present?
      @reports = @reports.where("report_type ILIKE ?", "%#{params[:report_type]}%")
    end

    if params[:start_date].present?
      start_date = Date.strptime(params[:start_date])
      @reports = @reports.where('generated_date >= ?', start_date)
    end

    if params[:end_date].present?
      end_date = Date.strptime(params[:end_date])
      @reports = @reports.where('generated_date <= ?', end_date)
    end
    @reports = @reports.order(generated_date: :desc).page(params[:page]).per(10)
  end

  def show
  end


  def new
    @company = Company.find(params[:company_id])
    @report = Report.new
  end

  def create
    @company = Company.find(params[:company_id])
    @report = @company.reports.new(report_params)

    # Extract dynamic filters from params
    filters = {}
    case params[:report][:report_type]
    when 'tipo_1' # Pagos de nómina
      filters[:employee] = params[:report][:filters_employee]
      filters[:start_date] = params[:report][:filters_start_date_1]
      filters[:end_date] = params[:report][:filters_end_date_1]
    when 'tipo_2' # Pagos de servicios prestados
      filters[:contractor] = params[:report][:filters_contractor]
      filters[:start_date] = params[:report][:filters_start_date]
      filters[:end_date] = params[:report][:filters_end_date]
    when 'tipo_3' # Vacaciones y enfermedad acumuladas
      filters[:employee] = params[:report][:filters_employee_2]
    when 'tipo_4' # Hours Report
      filters[:start_date] = params[:report][:filters_start_date_4]
      filters[:end_date] = params[:report][:filters_end_date_4]
    when 'tipo_5' # Social Security and Medicare Deposits Report
      filters[:year] = params[:report][:filters_year_5]
    when 'tipo_6' # Income Tax Deposits Report
      filters[:year] = params[:report][:filters_year_6]
    when 'tipo_7' # Service Payments Deposits Report
      filters[:year] = params[:report][:filters_year_7]
    end

    @report.filters = filters
    @report.generated_date = Time.current

    if @report.save
      redirect_to company_reports_path, notice: 'Reporte creado con éxito.'
    else
      render :new
    end
  end

  def destroy
    @report = Report.find(params[:id])
    @report.destroy
    redirect_to company_reports_path, notice: 'Reporte eliminado'
  end

  def download
    report = Report.find(params[:id])
    # Generar el archivo Excel
    report_file = report.generate_report

    # Enviar el archivo al cliente
    send_data report_file,
               filename: "#{report.type_name}.xlsx",
               type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
  end

  private

  def report_params
    params.require(:report).permit(:report_type, :generated_date)
  end
end

app/views/reports/edit.html.erb
<h1>Reports#edit</h1>
<p>Find me in app/views/reports/edit.html.erb</p>

app/views/reports/index.html.erb
<section id="reportes-index">
  <div class="view-options">
    <h1>Reportes Generados</h1>

    <!-- Filter options -->
    <div class="search-bar" data-controller="payrolldates">
        <%= form_with url: company_reports_path(@company), method: :get, local: true do %>

          <%= select_tag :report_type, options_for_select([['Pagos de nomina', 'tipo_1'], ['Pagos de servicios prestados', 'tipo_2'], ['Vacaciones y enfermedad acumuladas', 'tipo_3']], params[:report_type]), prompt: 'Seleccione un tipo de reporte' %>
          <%= label_tag :start_date, "Fecha de inicio" %>
          <%= date_field_tag :start_date, params[:start_date], data: { payrolldates_target: "periodStart" } %>
          <%= label_tag :end_date, "Fecha de fin" %>
          <%= date_field_tag :end_date, params[:end_date], data: { payrolldates_target: "periodEnd" } %>
          <%= submit_tag "Buscar", class: "btn btn-secondary" %>
          <% if params[:report_type].present? || params[:end_date].present? || params[:end_date].present? %>
            <%= link_to "Limpiar filtros", company_reports_path(@company), class: "btn btn-secondary" %>
          <% end %>
        <% end %>
      </div>

    <%= link_to "Crear reporte", new_company_report_path(@company), class: 'btn btn-primary' %>
  </div>



  <!--table details -->
  <table>
    <thead class="header-table">
      <tr>
        <th>N°</th>
        <th>Fecha de reporte</th>
        <th>Tipo de reporte</th>
        <th>Filtros</th>
        <th>Acciones</th>

      </tr>
    </thead>
    <tbody>
      <% @reports.order(created_at: :desc).each_with_index do |report, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= report.created_at %></td>
          <td><%= report.type_name %></td>
          <td><%= report.filters_formatted %></td>
          <td>
            <%= link_to "Imprimir reporte", download_report_path(report), class: "btn btn-primary" %>
            <%= link_to "Borrar reporte", company_report_path(@company, report),
                data: { turbo_method: :delete, turbo_confirm: "¿Estás seguro de que desear eliminar este reporte?" },
                class: "btn btn-danger btn-sm" %>

          </td>

        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @reports %>

</section>

<style>
  #reportes-index {
    padding-top: 0.5rem;
    padding-left: 1.5rem;
    padding-right: 1.5rem;
  }
</style>

app/views/reports/new.html.erb
<section id="new-report">
  <div class="form-container" data-controller="report-form">

    <h1>Crear Reporte</h1>

    <%= form_with model: [@company, @report], local: true do |form| %>

      <div class="detail-item">
        <%= form.hidden_field :generated_date, value: Date.today %>
      </div>

      <div class="detail-item">
        <%= form.label :report_type, "Tipo de reporte" %>
        <%= form.select :report_type,
          [
            ['Pagos de nomina', 'tipo_1'],
            ['Pagos de servicios prestados', 'tipo_2'],
            ['Vacaciones y enfermedad acumuladas', 'tipo_3'],
            ['Informe de horas', 'tipo_4'],
            ['Informe de depósitos de Seguro Social y Medicare', 'tipo_5'],
            ['Informe de depósitos de Impuesto sobre Ingresos', 'tipo_6'],
            ['Informe de depósitos de Pagos por Servicios', 'tipo_7']
          ],
          { prompt: 'Seleccione un tipo de reporte' },
          {
            class: 'input-span',
            "data-report-form-target": "reportType",
            data: {
              action: "change->report-form#updateFilters",
            }
          } %>
      </div>

      <div id="filters-section">
        <!-- Filters for "Pagos de nomina" -->
        <div class="filter-group" data-filter-type="tipo_1" data-report-form-target="filterGroup" style="display: none;">
          <%= form.label :employee, "Empleado" %>
          <%= form.select :filters_employee,
              [['Todos', 'all']] + @company.employees.order(first_name: :asc).map { |e| [e.full_name, e.id] },
              { class: 'input-span', selected: 'all' }
               %>

          <%= form.label :start_date, "Fecha de inicio" %>
          <%= form.date_field :filters_start_date_1, class: 'input-span', value: Date.current.beginning_of_year %>

          <%= form.label :end_date, "Fecha de fin" %>
          <%= form.date_field :filters_end_date_1, class: 'input-span' %>
        </div>

        <!-- Filters for "Pagos de servicios prestados" -->
        <div class="filter-group" data-filter-type="tipo_2" data-report-form-target="filterGroup" style="display: none;">
          <%= form.label :contractor, "Contratista" %>
          <%= form.select :filters_contractor,
            [['Todos', 'all']] + @company.contractors.order(first_name: :asc).map {|e| [e.full_name, e.id]},
            { class: 'input-span', selected: 'all' } %>

          <%= form.label :start_date, "Fecha de inicio" %>
          <%= form.date_field :filters_start_date, class: 'input-span', value: Date.current.beginning_of_year %>

          <%= form.label :end_date, "Fecha de fin" %>
          <%= form.date_field :filters_end_date, class: 'input-span' %>
        </div>

        <!-- Filters for "Vacaciones y enfermedad acumuladas" -->
        <div class="filter-group" data-filter-type="tipo_3" data-report-form-target="filterGroup" style="display: none;">
          <%= form.label :employee, "Empleado" %>
          <%= form.select :filters_employee_2,
              [['Todos', 'all']] + @company.employees.map { |e| [e.full_name, e.id] },
              { class: 'input-span', selected: 'all' } %>
        </div>

        <!-- Filters for "Informe de horas" -->
        <div class="filter-group" data-filter-type="tipo_4" data-report-form-target="filterGroup" style="display: none;">
          <%= form.label :start_date, "Fecha de inicio" %>
          <%= form.date_field :filters_start_date_4, class: 'input-span', value: Date.current.beginning_of_year %>

          <%= form.label :end_date, "Fecha de fin" %>
          <%= form.date_field :filters_end_date_4, class: 'input-span' %>
        </div>

        <!-- Filters for "Informe de depósitos de Seguro Social y Medicare" -->
        <div class="filter-group" data-filter-type="tipo_5" data-report-form-target="filterGroup" style="display: none;">
          <%= form.label :year, "Año" %>
          <%= form.select :filters_year_5,
              (2020..Date.current.year).map { |year| [year, year] },
              { class: 'input-span', selected: Date.current.year } %>
        </div>

        <!-- Filters for "Informe de depósitos de Impuesto sobre Ingresos" -->
        <div class="filter-group" data-filter-type="tipo_6" data-report-form-target="filterGroup" style="display: none;">
          <%= form.label :year, "Año" %>
          <%= form.select :filters_year_6,
              (2020..Date.current.year).map { |year| [year, year] },
              { class: 'input-span', selected: Date.current.year } %>
        </div>

        <!-- Filters for "Informe de depósitos de Pagos por Servicios" -->
        <div class="filter-group" data-filter-type="tipo_7" data-report-form-target="filterGroup" style="display: none;">
          <%= form.label :year, "Año" %>
          <%= form.select :filters_year_7,
              (2020..Date.current.year).map { |year| [year, year] },
              { class: 'input-span', selected: Date.current.year } %>
        </div>
      </div>

      <div class="button-group title-item">
        <%= link_to "Cancelar", company_reports_path(@company), class: "btn btn-danger" %>
        <%= form.submit "Crear Reporte", class: 'btn btn-primary' %>
      </div>

    <% end %>
  </div>
</section>

<style>
  #new-report {
    display: flex;
    flex-direction: column;
    gap: 20px;
    padding: 2rem;
    align-items: center;
  }
</style>

app/views/reports/show.html.erb
<h1>Reports#show</h1>
<p>Find me in app/views/reports/show.html.erb</p>