config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "companies#index"
  resources :companies do
    resources :employees do
      resources :payrolls
    end
    resources :parameters
    resources :payrolls
    resources :contractors do
      resources :service_payments
    end
    resources :service_payments
    resources :reports, only: [:index, :new, :create, :destroy, :show]
    resources :report_configurations
  end

  get "reports/:id/download" => "reports#download", as: :download_report
  get "pages/terms_and_conditions", to: "pages#terms_and_conditions"
  post "pages/update_terms_and_conditions", to: "pages#update_terms_and_conditions"
  get "pages/privacy_policy", to: "pages#privacy_policy"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/service_payment.rb
class ServicePayment < ApplicationRecord
  belongs_to :contractor

  validates :payment_date, :contractor_id, presence: true
  # validate :at_least_one_amount_present


  def company
    contractor.company
  end

  def calculate_year_to_date(field_name)
    year_start_date = payment_date.beginning_of_year
    contractor.service_payments.where('payment_date >= ? AND payment_date <= ?', year_start_date, payment_date).sum(field_name)
  end

  def calculate_year_to_date_total_amount
    calculate_year_to_date("amount_a") + calculate_year_to_date("amount_b") + calculate_year_to_date("amount_c")
  end

  private

  def at_least_one_amount_present
    if amount_a.blank? && amount_b.blank? && amount_c.blank?
      errors.add(:base, "At least one amount (amount_a, amount_b, or amount_c) must be present")
    end
  end
end

app/controllers/service_payments_controller.rb
class ServicePaymentsController < ApplicationController
  before_action :set_company
  before_action :set_contractor, only: [:new]
  def index
    @service_payments = ServicePayment.joins(:contractor).where(contractors: { company_id: @company.id }).includes(:contractor)

    if params[:search].present?
      @service_payments = @service_payments.where("CONCAT(contractors.first_name, ' ', contractors.last_name) ILIKE ?", "%#{params[:search]}%")
    end

    if params[:start_date].present?
      start_date = Date.strptime(params[:start_date])
      @service_payments = @service_payments.where('payment_date >= ?', start_date)
    end

    if params[:end_date].present?
      end_date = Date.strptime(params[:end_date])
      @service_payments = @service_payments.where('payment_date <= ?', end_date)
    end

    @service_payments = @service_payments.order(payment_date: :desc).page(params[:page]).per(10)

  end

  def new
    @contractors = @company.contractors
    @service_payment = ServicePayment.new
  end

  def show
    @service_payment = ServicePayment.find(params[:id])
    @company = current_user.companies.find(params[:company_id])

    respond_to do |format|
      format.html
      format.pdf do
        reporter = ServicePaymentReporter.new(@service_payment, @company)
        pdf = reporter.generate
        send_data pdf.render,
                  filename: "service_payment_report_#{@service_payment.id}.pdf",
                  type: 'application/pdf',
                  disposition: 'attachment'
      end
    end
  end

  def create
    @service_payment = ServicePayment.new(service_payment_params)

    if @service_payment.save
      redirect_to company_service_payments_path(@company), notice: 'Service payment was successfully created.'
    else
      render :new
    end
  end

  def edit
    @contractors = @company.contractors
    @service_payment = ServicePayment.find(params[:id])
    @contractor = @service_payment.contractor
  end


  def update
    @service_payment = ServicePayment.find(params[:id])
    if @service_payment.update(service_payment_params)
      redirect_to company_service_payments_path(@company, @service_payment), notice: 'Payroll was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @service_payment = ServicePayment.find(params[:id])
    @service_payment.destroy
    redirect_to company_service_payments_path(@company), notice: 'Payroll was successfully deleted.'
  end

  private

  def set_company
    @company = Company.find(params[:company_id])
  end

  def set_contractor
    @contractor = @company.contractors.find_by(id: params[:contractor_id]) if params[:contractor_id]
  end

  def service_payment_params
    params.require(:service_payment).permit(
      :contractor_id,
      :gross_amount,
      :deduction_amount,
      :net_amount,
      :payment_date,
      :paid_to_individuals_no_retention,
      :paid_to_corporation_no_retention,
      :paid_to_individuals_with_retention,
      :retention_percentage_individuals,
      :retention_individuals,
      :paid_to_corporation_with_retention,
      :retention_percentage_corporations,
      :retention_corporations,
      :reimbursed_expenses,
      :responsibility_payment_health_providers,
      :special_contribution_services,
      :payment_method,
      :period_start,
      :period_end
    )
  end
end

app/views/service_payments/_form.html.erb
<div class="form-container" data-controller="service-payment-calculations">
  <%= simple_form_for([company, contractor, service_payment], html: { class: 'details-container', local: true }) do |f| %>
    <div class="title-item">
      <h5>Crear Nuevo Pago de Servicio</h5>
    </div>

    <!-- Sección: Selección de Contratista -->
    <div class="payroll-dates-card" data-controller="payrolldates">
      <%= f.input :contractor_id,
                  collection: contractors.order(first_name: :asc),
                  label: "Contratistas",
                  prompt: "Seleccione un contratista",
                  as: :select,
                  value_method: :id,
                  label_method: :full_name,
                  wrapper_html: { class: 'detail-item' },
                  label_html: { class: 'label-bold' },
                  input_html: { class: 'input-span' } %>
      <%= f.input :payment_method,
              collection: ["Transferencia", "Cheque", "Efectivo", "Otro"],
              label: "Método de Pago",
              prompt: "Seleccionar Método de Pago",
              as: :select,
              wrapper_html: { class: 'detail-item' },
              label_html: { class: 'label-bold' },
              input_html: {
                class: 'input-span',
                data: {
                  action: "change->payrolls-calculations#showFields",
                  payrolls_calculations_target: "paymentMethod"

                } } %>

      <%= f.input :period_start, label: "Fecha de Inicio",
                        as: :string,
                        wrapper_html: { class: 'detail-item' },
                        label_html: { class: 'label-bold' },
                        input_html: {
                          class: 'input-span',
                          data: {
                            payrolldates_target: "periodStart",
                            action: "change->payrolldates#updatePeriodEndMinDate",
                            action: "change->payrolls-calculations#showFields",
                            payrolls_calculations_target: "period_start"
                                  } } %>

        <%= f.input :period_end, label: "Fecha de Fin",
                        as: :string,
                        wrapper_html: { class: 'detail-item' },
                        label_html: { class: 'label-bold' },
                        input_html: {
                          class: 'input-span',
                          data: {
                            payrolldates_target: "periodEnd",
                            action: "change->payrolls-calculations#showFields",
                            payrolls_calculations_target: "period_end"
                                  } } %>


      <%= f.input :payment_date, label: "Fecha de pago",
                  as: :string,
                  wrapper_html: { class: 'detail-item' },
                  label_html: { class: 'label-bold' },
                  input_html: {
                    class: 'input-span',
                    data: {
                          payrolldates_target: "payDate",
                          action: "change->payrolls-calculations#showFields",
                          payrolls_calculations_target: "pay_date"}} %>
    </div>

    <!-- Sección: Cantidades -->
    <div class="section-container">
      <div class="section-header">
        <h5>Detalles de Pago</h5>
      </div>
      <div class="services-group">
        <div class="grid-services">
          <%= f.input :paid_to_individuals_no_retention,
                    label: "Pagos a individuales no sujetos a retención",
                    wrapper_html: { class: 'service-inputs-wraps' },
                    placeholder: "0",
                    label_html: { class: 'service-label-span' },
                    input_html: { class: 'service-inputs-span', type: "number", step: 1, min: 0,
                    data: {
                        service_payment_calculations_target: "paidToIndividualsNoRetention",
                        action: "change->service-payment-calculations#servicePaymentCalculations"
                      } } %>
        </div>
        <div class="grid-services">
          <%= f.input :paid_to_corporation_no_retention,
                      label: "Pago a corporaciones no sujetas a retención",
                      placeholder: "0",
                      wrapper_html: { class: 'service-inputs-wraps' },
                      label_html: { class: 'service-label-span' },
                      input_html: { class: 'service-inputs-span', type: "number", step: 1, min: 0,
                      data: {
                          service_payment_calculations_target: "paidToCorporationNoRetention",
                          action: "change->service-payment-calculations#servicePaymentCalculations"
                        } } %>
        </div>

        <!--- Block retention to individuals -->
        <div class="grid-services">
          <%= f.input :paid_to_individuals_with_retention,
                    label: "Pago a individuales sujetos a retención",
                    placeholder: "0",
                    wrapper_html: { class: 'service-inputs-wraps' },
                    label_html: { class: 'service-label-span' },
                    input_html: { class: 'service-inputs-span',
                    data: {
                        service_payment_calculations_target: "paidToIndividualsWithRetention",
                        action: "change->service-payment-calculations#servicePaymentCalculations"
                      } } %>

          <%= f.input :retention_percentage_individuals,
                      label: "% de retención a individuales",
                      collection: [["0%", 0], ["4%", 4], ["6%", 6], ["8%", 8], ["10%", 10], ["15%", 15], ["20%", 20]],
                      selected: 0,
                      wrapper_html: { class: 'service-inputs-wraps' },
                      label_html: { class: 'service-label-span' },
                      input_html: { class: 'service-inputs-span', type: "number", step: 1, min: 0,
                      data: {
                          service_payment_calculations_target: "retentionPercentageIndividuals",
                          action: "change->service-payment-calculations#servicePaymentCalculations"
                        } } %>

          <%= f.input :retention_individuals,
                      label: "Retención a individuales",
                      placeholder: "0",
                      wrapper_html: { class: 'service-inputs-wraps' },
                      label_html: { class: 'service-label-span' },
                      input_html: {
                        class: 'service-inputs-span readonly-field',
                        readonly: true,
                        data: { service_payment_calculations_target: "retentionIndividuals" } } %>
        </div>


        <!--- Block retention to corporations -->
        <div class="grid-services">
          <%= f.input :paid_to_corporation_with_retention,
                    label: "Pago a corporaciones sujetas a retención",
                    placeholder: "0",
                    wrapper_html: { class: 'service-inputs-wraps' },
                    label_html: { class: 'service-label-span' },
                      input_html: { class: 'service-inputs-span', type: "number", step: 1, min: 0,
                    data: {
                        service_payment_calculations_target: "paidToCorporationWithRetention",
                        action: "change->service-payment-calculations#servicePaymentCalculations"
                      } } %>

          <%= f.input :retention_percentage_corporations,
                      label: "% de retención a corporaciones",
                      collection: [["0%", 0], ["4%", 4], ["6%", 6], ["8%", 8], ["10%", 10], ["15%", 15], ["20%", 20]],
                      selected: 0,
                      wrapper_html: { class: 'service-inputs-wraps' },
                      label_html: { class: 'service-label-span' },
                      input_html: { class: 'service-inputs-span', type: "number", step: 1, min: 0,
                      data: {
                          service_payment_calculations_target: "retentionPercentageCorporation",
                          action: "change->service-payment-calculations#servicePaymentCalculations"
                        } } %>
          <%= f.input :retention_corporations,
                      label: "Retención a coroporaciones",
                      placeholder: "0",
                      wrapper_html: { class: 'service-inputs-wraps' },
                      label_html: { class: 'service-label-span' },
                      input_html: {
                        class: 'service-inputs-span readonly-field',
                        readonly: true,
                        data: { service_payment_calculations_target: "retentionCorporation" } } %>
        </div>
        <div class="grid-services">
          <%= f.input :reimbursed_expenses,
                    label: "Gastos Reembolsados",
                    placeholder: "0",
                    wrapper_html: { class: 'service-inputs-wraps' },
                    label_html: { class: 'service-label-span' },
                      input_html: { class: 'service-inputs-span', type: "number", step: 1, min: 0,
                    data: {
                        service_payment_calculations_target: "reimbursedExpenses",
                        action: "change->service-payment-calculations#servicePaymentCalculations"
                      } } %>
        </div>

        <div class="grid-services">
          <%= f.input :responsibility_payment_health_providers,
                    label: "Responsabilidad de pago a proveedores de salud",
                    placeholder: "0",
                    wrapper_html: { class: 'service-inputs-wraps' },
                    label_html: { class: 'service-label-span' },
                      input_html: { class: 'service-inputs-span', type: "number", step: 1, min: 0,
                    data: {
                        service_payment_calculations_target: "responsibilityPaymentHealthProviders",
                        action: "change->service-payment-calculations#servicePaymentCalculations"
                      } } %>
        </div>

        <div class="grid-services">
          <%= f.input :special_contribution_services,
                    label: "Aportación especial por Servicio Profesionales y Consultivos bajo la Ley 48-2013",
                    placeholder: "0",
                    wrapper_html: { class: 'service-inputs-wraps' },
                    label_html: { class: 'service-label-span' },
                      input_html: { class: 'service-inputs-span', type: "number", step: 1, min: 0,
                    data: {
                        service_payment_calculations_target: "specialContributionServices",
                        action: "change->service-payment-calculations#servicePaymentCalculations"
                      } } %>
        </div>


        <!--- Block gross, deduction and net amount -->
        <div class="grid-services">
          <%= f.input :gross_amount,
                    label: "Monto Bruto",
                    placeholder: "0",
                    wrapper_html: { class: 'service-inputs-wraps' },
                    label_html: { class: 'service-label-span' },
                    input_html: { class: 'service-inputs-span readonly-field', readonly: true,
                      data: { service_payment_calculations_target: "grossAmount" } } %>
          <div></div>
           <%= f.input :deduction_amount,
                    label: "Monto de Deducción",
                    placeholder: "0",
                    wrapper_html: { class: 'service-inputs-wraps' },
                    label_html: { class: 'service-label-span' },
                    input_html: { class: 'service-inputs-span readonly-field', readonly: true,
                    data: {
                        service_payment_calculations_target: "deductionAmount",
                        action: "change->service-payment-calculations#servicePaymentCalculations"
                      }  } %>

          <%= f.input :net_amount,
                    label: "Monto Neto",
                    wrapper_html: { class: 'service-inputs-wraps' },
                    placeholder: "0",
                    label_html: { class: 'service-label-span' },
                    input_html: { class: 'service-inputs-span readonly-field', readonly: true,
                      data: { service_payment_calculations_target: "netAmount" } } %>
        </div>


      </div>
    </div>

    <!-- Botón de Envío -->
    <div class="button-group title-item">
      <%= link_to "Cancelar",  company_service_payments_path(company), class: "btn btn-danger" %>
      <%= f.button :submit, service_payment.new_record? ? "Crear Servicio Prestado": "Actualizar servicio prestado", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

<style>
  .form-container {

    background: #f9f9f9;
    border-radius: 8px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  }

  .title-item h5 {
    font-size: 1.5rem;
    margin-bottom: 1rem;
    color: #333;
  }

  .section-header h5 {
    font-size: 1.25rem;
    margin-bottom: 1rem;
    color: #555;
  }


  .readonly-field {
    background: #e9ecef;
    color: #6c757d;
    cursor: not-allowed;
  }

</style>

app/views/service_payments/edit.html.erb
<section id="edit-service-payments">
  <%= render "form", company: @company, contractors: @contractors, contractor: @contractor, service_payment: @service_payment %>

</section>


<style>

  #edit-service-payments {
    display: flex;
    flex-direction: column;

    gap: 20px;
    padding: 2rem;

    align-items: center;
  }




</style>

app/views/service_payments/index.html.erb
<section id="service-payments-index">
  <div class="view-options">
    <% if @contractor %>
      <h1>Pagos de Servicio para <%= @contractor.name %></h1>
      <%= link_to 'Crear Pago de Servicio', new_company_contractor_service_payment_path(@company, @contractor), class: 'btn btn-primary' %>
    <% else %>
      <h1>Pagos de Servicios</h1>

      <!-- Filter options-->
      <div class="search-bar"  data-controller="payrolldates">
        <%= form_with url: company_service_payments_path(@company), method: :get, local: true do %>
          <%= label_tag :search, "Contratista" %>
          <%= text_field_tag :search, params[:search], placeholder: "Contratista" %>
          <%= label_tag :start_date, "Fecha de inicio" %>
          <%= date_field_tag :start_date, params[:start_date], data: { payrolldates_target: "periodStart" } %>
          <%= label_tag :end_date, "Fin" %>
          <%= date_field_tag :end_date, params[:end_date], data: { payrolldates_target: "periodEnd" } %>
          <%= submit_tag "Buscar", class: "btn btn-secondary" %>
          <% if params[:search].present? || params[:start_date].present? || params[:end_date].present? %>
            <%= link_to "Limpiar filtros", company_service_payments_path(@company), class: "btn btn-secondary" %>
          <% end %>
        <% end %>
      </div>

      <%= link_to 'Crear Pago de Servicio', new_company_service_payment_path(@company), class: 'btn btn-primary' %>
    <% end %>
    <!-- Opciones de filtro, si son necesarias, pueden agregarse aquí -->
  </div>

  <!-- Tabla de detalles -->

  <table>
    <thead class="header-table">
      <tr>
        <th>N°</th>
        <th>Fecha de Pago</th>
        <th>Contratista</th>
        <th>Importe Bruto</th>

        <th>Importe de Deducción</th>
        <th>Importe Neto</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      <% @service_payments.order(payment_date: :desc).each_with_index do |payment, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= payment.payment_date %></td>
          <td><%= link_to payment.contractor.full_name, company_contractor_path(@company, payment.contractor) %></td>
          <td><%= number_to_currency(payment.gross_amount) %></td>

          <td><%= number_to_currency(payment.deduction_amount) %></td>
          <td><%= number_to_currency(payment.net_amount) %></td>
          <td>
            <%= link_to "Imprimir", company_service_payment_path(@company, payment, format: :pdf), class: "btn btn-primary"  %>
            <%= link_to "Editar", edit_company_contractor_service_payment_path(@company, payment.contractor, payment), class: "btn btn-primary"  %>
            <%= link_to "Eliminar", company_service_payment_path(@company, payment),
                data: { turbo_method: :delete, turbo_confirm: "¿Estás seguro de que deseas eliminar este pago de servicio?" },
                class: "btn btn-danger btn-sm" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @service_payments %>

</section>

<style>
  #service-payments-index {
    padding: 2rem;
  }

  #service-payments-index h1 {
    margin-bottom: 1rem;
    font-size: 1.5rem;
  }


</style>

app/views/service_payments/new.html.erb
<section id="new-service-payments">
  <%= render "form", company: @company, contractors: @contractors, contractor: @contractor, service_payment: @service_payment %>
</section>


<style>

  #new-service-payments {
    display: flex;
    flex-direction: column;
    gap: 20px;
    padding: 2rem;
    align-items: center;
  }




</style>

app/views/service_payments/reporte.pdf.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Hola mundo</h1>
  <h2>Prueba 2</h2>
  <p>hjddjdjdjcdcdbdj</p>
</body>
</html>